### ISSUE TITLE
Does it work on the Ti CX II?

### ISSUE THREAD

**Issue by MarioYT21** [grubbyplaya/Sonic-2-CE#2]
I tried loading it up on my Ti CX II but it doesn't load due to incompatible file name. Is it only compatible with the TI-84?

**Comment by grubbyplaya** [comment]
Sonic 2 CE is only playable on the TI-84+ CE. If you want to play Sonic on a Nspire, [check](https://www.ticalc.org/archives/files/fileinfo/467/46743.html) [these](https://www.ticalc.org/archives/files/fileinfo/465/46547.html) [out](https://www.ticalc.org/archives/files/fileinfo/449/44971.html).
